import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";
import { PHOTO_SETS, FALLBACK_PHOTO } from "../scripts/photo-urls";

const prisma = new PrismaClient();

async function main() {
  const password = await bcrypt.hash("password123", 10);

  const admin = await prisma.user.upsert({
    where: { email: "admin@davaorent.com" },
    update: {},
    create: {
      email: "admin@davaorent.com",
      name: "DavaoRent Admin",
      password,
      role: "ADMIN",
      verifiedEmail: true,
      verifiedPhone: true,
      verifiedIdentity: true,
    },
  });

  const owner = await prisma.user.upsert({
    where: { email: "owner@davaorent.com" },
    update: {},
    create: {
      email: "owner@davaorent.com",
      name: "Maria Santos",
      phone: "09171234567",
      password,
      role: "OWNER",
      verifiedEmail: true,
      verifiedPhone: true,
      verifiedIdentity: true,
    },
  });

  const owner2 = await prisma.user.upsert({
    where: { email: "broker@davaorent.com" },
    update: {},
    create: {
      email: "broker@davaorent.com",
      name: "Davao Prime Realty",
      phone: "09181234567",
      password,
      role: "AGENCY",
      verifiedEmail: true,
      verifiedPhone: true,
    },
  });

  await prisma.user.upsert({
    where: { email: "renter@davaorent.com" },
    update: {},
    create: {
      email: "renter@davaorent.com",
      name: "Juan Dela Cruz",
      phone: "09201234567",
      password,
      role: "RENTER",
      verifiedEmail: true,
      verifiedPhone: true,
    },
  });

  const listings = [
    {
      ownerId: owner.id,
      title: "Cozy 1BR Apartment near Matina Town Square",
      description:
        "Fully furnished 1-bedroom apartment a short walk from Matina Town Square. Quiet compound with gated entrance, ideal for young professionals. Water included in rent.",
      category: "APARTMENT",
      price: 12000,
      deposit: 12000,
      advance: 12000,
      district: "Talomo",
      barangay: "Matina Crossing",
      addressFull: "123 Sample St, Matina Crossing, Davao City",
      landmark: "Near Matina Town Square",
      bedrooms: 1,
      bathrooms: 1,
      floorArea: 32,
      furnished: true,
      aircon: true,
      internet: true,
      parking: true,
      minStayMonths: 6,
      amenities: JSON.stringify(["CCTV", "Gated compound", "Own meter"]),
      houseRules: JSON.stringify(["No smoking indoors", "Max 2 occupants"]),
      status: "PUBLISHED",
      featured: true,
      verifiedProperty: true,
      seedPhoto: 101,
    },
    {
      ownerId: owner.id,
      title: "Bedspace for Students near Ateneo de Davao",
      description:
        "Affordable bedspace in a clean boarding house along Jacinto St. Walking distance to Ateneo de Davao University. WiFi and utilities included.",
      category: "BEDSPACE",
      price: 2500,
      deposit: 2500,
      advance: 2500,
      district: "Poblacion",
      barangay: "Poblacion District 1",
      addressFull: "45 Jacinto St, Poblacion, Davao City",
      landmark: "Near Ateneo de Davao",
      bedrooms: 1,
      bathrooms: 2,
      internet: true,
      utilitiesIncluded: true,
      minStayMonths: 1,
      amenities: JSON.stringify(["WiFi", "Shared kitchen", "Laundry area"]),
      houseRules: JSON.stringify(["Curfew 11 PM", "No visitors in rooms"]),
      status: "PUBLISHED",
      verifiedProperty: true,
      seedPhoto: 102,
    },
    {
      ownerId: owner2.id,
      title: "Modern Studio Condo at Avida Towers Abreeza",
      description:
        "Sleek studio unit with city view at Avida Towers, beside Abreeza Mall. Pool, gym, and 24/7 security. Perfect for professionals working along J.P. Laurel Ave.",
      category: "CONDO",
      price: 18000,
      deposit: 18000,
      advance: 36000,
      district: "Poblacion",
      barangay: "Bajada",
      addressFull: "Avida Towers, J.P. Laurel Ave, Bajada, Davao City",
      landmark: "Beside Abreeza Mall",
      bedrooms: 0,
      bathrooms: 1,
      floorArea: 24,
      furnished: true,
      aircon: true,
      internet: true,
      parking: true,
      minStayMonths: 12,
      amenities: JSON.stringify(["Pool", "Gym", "24/7 security", "Elevator"]),
      houseRules: JSON.stringify(["No pets", "No smoking"]),
      status: "PUBLISHED",
      featured: true,
      seedPhoto: 103,
    },
    {
      ownerId: owner.id,
      title: "3BR House with Garage in Buhangin",
      description:
        "Spacious 3-bedroom house in a quiet subdivision in Buhangin. Two-car garage, small garden, pet-friendly. Near Gaisano Grand Buhangin.",
      category: "HOUSE",
      price: 25000,
      deposit: 25000,
      advance: 25000,
      district: "Buhangin",
      barangay: "Buhangin Proper",
      addressFull: "Blk 5 Lot 2, Sample Subdivision, Buhangin, Davao City",
      landmark: "Near Gaisano Grand Buhangin",
      bedrooms: 3,
      bathrooms: 2,
      floorArea: 120,
      petFriendly: true,
      parking: true,
      minStayMonths: 12,
      amenities: JSON.stringify(["Garage", "Garden", "Gated subdivision"]),
      houseRules: JSON.stringify(["Max 6 occupants"]),
      status: "PUBLISHED",
      verifiedProperty: true,
      seedPhoto: 104,
    },
    {
      ownerId: owner2.id,
      title: "Room for Rent in Toril, Near Public Market",
      description:
        "Clean private room with own bathroom in Toril. Near jeepney routes and Toril public market. Ideal for workers in the area.",
      category: "ROOM",
      price: 4500,
      deposit: 4500,
      advance: 4500,
      district: "Toril",
      barangay: "Toril Proper",
      addressFull: "88 Sample Rd, Toril, Davao City",
      landmark: "Near Toril Public Market",
      bedrooms: 1,
      bathrooms: 1,
      internet: true,
      minStayMonths: 3,
      amenities: JSON.stringify(["Own bathroom", "Own entrance"]),
      houseRules: JSON.stringify(["No loud music after 10 PM"]),
      status: "PUBLISHED",
      seedPhoto: 105,
    },
    {
      ownerId: owner2.id,
      title: "Commercial Space along Quimpo Boulevard",
      description:
        "Ground-floor commercial space, 60 sqm, high foot traffic along Quimpo Blvd. Suitable for food business, pharmacy, or retail.",
      category: "COMMERCIAL",
      price: 45000,
      deposit: 90000,
      advance: 45000,
      district: "Talomo",
      barangay: "Bucana",
      addressFull: "Quimpo Blvd, Bucana, Davao City",
      landmark: "Near SM City Davao",
      bedrooms: 0,
      bathrooms: 1,
      floorArea: 60,
      parking: true,
      minStayMonths: 12,
      amenities: JSON.stringify(["High foot traffic", "3-phase power"]),
      houseRules: JSON.stringify([]),
      status: "PUBLISHED",
      seedPhoto: 106,
    },
    {
      ownerId: owner.id,
      title: "Boarding House Room in Agdao",
      description:
        "Simple, budget-friendly room in Agdao boarding house. Shared kitchen and bathroom. Near Agdao public market and downtown jeepney routes.",
      category: "BOARDING_HOUSE",
      price: 3500,
      deposit: 3500,
      advance: 3500,
      district: "Agdao",
      barangay: "Agdao Proper",
      addressFull: "12 Sample St, Agdao, Davao City",
      landmark: "Near Agdao Public Market",
      bedrooms: 1,
      bathrooms: 1,
      minStayMonths: 1,
      amenities: JSON.stringify(["Shared kitchen", "Water included"]),
      houseRules: JSON.stringify(["Curfew 12 MN"]),
      status: "PUBLISHED",
      seedPhoto: 107,
    },
    {
      ownerId: owner2.id,
      title: "2BR Apartment in Lanang, Near SM Lanang Premier",
      description:
        "Well-maintained 2-bedroom apartment in Lanang, 5 minutes from SM Lanang Premier. Semi-furnished with kitchen cabinets and aircon in master bedroom.",
      category: "APARTMENT",
      price: 16000,
      deposit: 16000,
      advance: 16000,
      district: "Buhangin",
      barangay: "Lanang",
      addressFull: "77 Sample Ave, Lanang, Davao City",
      landmark: "Near SM Lanang Premier",
      bedrooms: 2,
      bathrooms: 1,
      floorArea: 55,
      aircon: true,
      parking: true,
      internet: true,
      minStayMonths: 6,
      amenities: JSON.stringify(["Kitchen cabinets", "Balcony"]),
      houseRules: JSON.stringify(["No subletting"]),
      status: "PUBLISHED",
      featured: true,
      seedPhoto: 108,
    },
  ];

  const otherRentals = [
    {
      ownerId: owner2.id,
      title: "Toyota Vios 2022 — Self-Drive Car Rental",
      description:
        "Well-maintained Toyota Vios 2022, automatic, cold aircon. Self-drive within Davao Region; with-driver option available. Comprehensive insurance and 24/7 roadside support included. Valid driver's license and one government ID required.",
      category: "CAR",
      price: 1800,
      priceUnit: "DAY",
      deposit: 5000,
      advance: 0,
      district: "Poblacion",
      barangay: "Bajada",
      addressFull: "Unit 4, Sample Bldg, J.P. Laurel Ave, Bajada, Davao City",
      landmark: "Near Victoria Plaza",
      bedrooms: 0,
      bathrooms: 0,
      minStayMonths: 1,
      amenities: JSON.stringify(["Comprehensive insurance", "Unlimited km within Davao", "Bluetooth stereo", "With-driver option"]),
      houseRules: JSON.stringify(["Valid driver's license required", "No smoking inside", "Return with same fuel level"]),
      status: "PUBLISHED",
      featured: true,
      seedPhoto: 121,
    },
    {
      ownerId: owner.id,
      title: "Honda Click 125i Scooter Rental — Daily or Weekly",
      description:
        "Fuel-efficient Honda Click 125i, perfect for commuting around Davao. Two free helmets included. Daily and discounted weekly rates. Registered, insured, and regularly serviced.",
      category: "MOTORCYCLE",
      price: 500,
      priceUnit: "DAY",
      deposit: 2000,
      advance: 0,
      district: "Talomo",
      barangay: "Matina Crossing",
      addressFull: "123 Sample St, Matina Crossing, Davao City",
      landmark: "Near Matina Town Square",
      bedrooms: 0,
      bathrooms: 0,
      minStayMonths: 1,
      amenities: JSON.stringify(["2 helmets included", "Phone holder", "Insured & registered"]),
      houseRules: JSON.stringify(["Valid license required", "City use only"]),
      status: "PUBLISHED",
      seedPhoto: 122,
    },
    {
      ownerId: owner2.id,
      title: "Power Tools & Jackhammer Set — Construction Equipment",
      description:
        "Heavy-duty jackhammer, rotary drills, angle grinder, and generator set for construction or renovation projects. Daily rates with operator option. Delivery within Davao City available.",
      category: "EQUIPMENT",
      price: 1200,
      priceUnit: "DAY",
      deposit: 3000,
      advance: 0,
      district: "Agdao",
      barangay: "Agdao Proper",
      addressFull: "12 Sample St, Agdao, Davao City",
      landmark: "Near Agdao Public Market",
      bedrooms: 0,
      bathrooms: 0,
      minStayMonths: 1,
      amenities: JSON.stringify(["Delivery available", "Operator option", "Safety gear included"]),
      houseRules: JSON.stringify(["Government ID required", "Damage fees apply"]),
      status: "PUBLISHED",
      seedPhoto: 123,
    },
    {
      ownerId: owner2.id,
      title: "Sound System & Lights Package for Events",
      description:
        "Complete events package: 2x 15-inch powered speakers, mixer, 2 wireless microphones, party lights, and technician for up to 6 hours. Ideal for birthdays, weddings, and corporate events around Davao.",
      category: "EVENT",
      price: 4500,
      priceUnit: "DAY",
      deposit: 2000,
      advance: 1000,
      district: "Buhangin",
      barangay: "Buhangin Proper",
      addressFull: "Blk 5 Lot 2, Sample Subdivision, Buhangin, Davao City",
      landmark: "Near Gaisano Grand Buhangin",
      bedrooms: 0,
      bathrooms: 0,
      minStayMonths: 1,
      amenities: JSON.stringify(["Technician included", "Free setup", "Backup equipment"]),
      houseRules: JSON.stringify(["Book at least 3 days ahead", "50% down payment to reserve"]),
      status: "PUBLISHED",
      featured: true,
      seedPhoto: 124,
    },
    {
      ownerId: owner.id,
      title: "Washing Machine Rental — Monthly Plan",
      description:
        "Fully automatic 8kg washing machine on a monthly rental plan. Free delivery, installation, and maintenance within Davao City. Swap-out unit provided if repairs are needed.",
      category: "APPLIANCE",
      price: 1200,
      priceUnit: "MONTH",
      deposit: 1200,
      advance: 0,
      district: "Toril",
      barangay: "Toril Proper",
      addressFull: "88 Sample Rd, Toril, Davao City",
      landmark: "Near Toril Public Market",
      bedrooms: 0,
      bathrooms: 0,
      minStayMonths: 3,
      amenities: JSON.stringify(["Free delivery & install", "Free maintenance", "Swap-out guarantee"]),
      houseRules: JSON.stringify(["3-month minimum", "Ground floor delivery only"]),
      status: "PUBLISHED",
      seedPhoto: 125,
    },
    {
      ownerId: owner2.id,
      title: "Cozy Vacation Suite near Roxas Night Market",
      description:
        "Stylish studio suite for short stays — walking distance to Roxas Night Market and downtown Davao. Fast WiFi, smart TV, kitchenette, and self check-in. Perfect for tourists and staycations.",
      category: "VACATION",
      price: 2200,
      priceUnit: "DAY",
      deposit: 1000,
      advance: 0,
      district: "Poblacion",
      barangay: "Poblacion District 1",
      addressFull: "45 Jacinto St, Poblacion, Davao City",
      landmark: "Near Roxas Night Market",
      bedrooms: 1,
      bathrooms: 1,
      furnished: true,
      aircon: true,
      internet: true,
      minStayMonths: 1,
      amenities: JSON.stringify(["Fast WiFi", "Smart TV", "Kitchenette", "Self check-in"]),
      houseRules: JSON.stringify(["No parties", "Max 2 guests", "Check-out 11 AM"]),
      status: "PUBLISHED",
      seedPhoto: 126,
    },
  ];
  listings.push(...(otherRentals as any));

  for (const l of listings) {
    const { seedPhoto: _seedPhoto, ...data } = l;
    const existing = await prisma.listing.findFirst({ where: { title: data.title } });
    if (existing) continue;
    const pool = PHOTO_SETS[data.category] ?? [FALLBACK_PHOTO];
    await prisma.listing.create({
      data: {
        ...data,
        availableFrom: new Date(),
        photos: {
          create: [0, 1, 2].map((i) => ({ url: pool[i % pool.length], isCover: i === 0, sort: i })),
        },
      },
    });
  }

  console.log("Seed complete.");
  console.log("Accounts (password: password123):");
  console.log("  admin@davaorent.com  (ADMIN)");
  console.log("  owner@davaorent.com  (OWNER)");
  console.log("  broker@davaorent.com (AGENCY)");
  console.log("  renter@davaorent.com (RENTER)");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
